id: P007975
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13764
  title: བོད་ཀྱི་ནང་མ་སྟོད་གཞས་ཀྱི་སྒྲ་གདངས།
  author: ''
  volumes:
    218a56512cc74d708bf6725ba5d0e3c4:
      image_group_id: I1KG14949
      title: ''
      volume_number: 1
      total_pages: 146
ebook_metadata:
  title: བོད་ཀྱི་ནང་མ་སྟོད་གཞས་ཀྱི་སྒྲ་གདངས།
  author: ''
  sku: P007975
  cover: cover.jpg
  layers:
  - pagination
