id: P007975
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 12:52:44.709248
source_metadata:
  id: bdr:W1KG13764
  title: བོད་ཀྱི་ནང་མ་སྟོད་གཞས་ཀྱི་སྒྲ་གདངས།
  author: ''
  volumes:
    2cf96bd6b9ae47beaeb98bae27b4b23b:
      image_group_id: I1KG14949
      title: Volume 1 of bod kyi nang ma stod gzhas kyi sgra gdangs/
      volume_number: 1
      total_pages: 146
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
